#!/bin/bash

apt-get install build-essential
apt-get install git tmux vim

# Initialize git submodules.
git submodule init
git submodule update

# Setup javascript development environment.
echo "Setting up Javascipt development environment..."
./javascript-setup

# Setup Ruby on Rails.
./RoR-setup

# Setup Java java development environment.
echo "Setting up JDK..."
cd jdk-ubuntu-setup
./jdk8-u101-linux-x64.sh
cd ..

# Copy tmux config.
cp .tmux.conf ~
