#!/bin/bash

# Install Elixir.
wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
apt-get update
esl-erlang
apt-get install esl-erlang elixir
elixir -v

# Install phoenix.
mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez
mix phoenix.new -v

# Install inotify-tools
apt-get install inotify-tools
