#!/bin/bash
sudo apt-get install dconf-cli
git clone https://github.com/Anthony25/gnome-terminal-colors-solarized.git
cd gnome-terminal-colors-solarized
./install.sh

echo
echo "#Solarized configuration." >> ~/.bashrc
echo 'export TERM=xterm-256color        # for common 256 color terminals (e.g. gnome-terminal)' >> ~/.bashrc
echo 'export TERM=screen-256color       # for a tmux -2 session (also for screen)' >> ~/.bashrc
