#!/bin/bash

# Add Oracle's PPA.
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update

# Download and install Oracle JDK8 because it is the most stable.
sudo apt-get install oracle-java8-installer

# Setup this java as the default.
sudo apt-get install oracle-java8-set-default

java -version
javac -version
javaws -version

echo "You may need to logout or restart to be able to apply changes to the JAVA_HOME."
