#!/bin/bash
sudo apt-get update
sudo apt-get install build-essential
sudo apt-get install git tmux vim xclip tig

rm ~/.tmux.conf
ln -n configs/.tmux.conf ~/.tmux.conf

rm ~/.bash_aliases
ln -n configs/.bash_aliases ~/.bash_aliases

echo "" >> ~/.bashrc
echo "export EDITOR=vim" >> ~/.bashrc

echo "" >> ~/.bashrc
echo "export PS1='\$ '" >> ~/.bashrc
echo "Restart to apply all changes."
