#!/bin/bash
sudo apt-get update
sudo apt-get install build-essential
sudo apt-get install git tmux vim xclip tig

rm ~/.tmux.conf
ln -n .tmux.conf ~/.tmux.conf

rm ~/.bash_aliases
ln -n .bash_aliases ~/.bash_aliases
