#!/bin/bash

# ls colors
git clone https://github.com/seebi/dircolors-solarized.git
mv dircolors-solarized/dircolors.ansi-dark ~/.dircolors
rm -rf dircolors-solarized

# Terminal configurations
echo "" >> ~/.bashrc
echo "#Solarized configuration." >> ~/.bashrc
echo 'export TERM=xterm-256color        # for common 256 color terminals (e.g. gnome-terminal)' >> ~/.bashrc
echo 'export TERM=screen-256color       # for a tmux -2 session (also for screen)' >> ~/.bashrc
